### ISSUE TITLE
subtractStockOfDrink() 함수 연산자 관련 문제  

### ISSUE THREAD

**Issue by S0okJu** [dmdrk1414/java_second_school_study#1]
https://github.com/dmdrk1414/java_second_school_study/blob/e923daa0568b7d4d7e880853d44a9145d109f51d/VendingMachine/src/vendingmachine/model/Drink.java#L27

`subtractStockOfDrink`는 현재 재고를 줄이는데 사용되는 걸로 이해하고 있습니다. 
함수의 파라미터를 음수로 받아야 하는건지, 음수로 받아야한다면 별도의 예외처리가 필요한 것 같습니다.  설령 양수로 받는다고 해도 현재 재고가 음수가 되지 않도록 예외처리가 필요하다고 생각합니다.

**Comment by dmdrk1414** [comment]
제가 검증하는 함수를 만들고 적용을 안했네요 다시 업데이트 하였습니다. 정말 감사합니다.
